
[functions.send-purchase-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-purchase-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-purchase-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-purchase-email/*.html" ]

[functions.moderate-content]
enabled = true
verify_jwt = true
import_map = "./functions/moderate-content/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/moderate-content/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/moderate-content/*.html" ]

[functions.get-analytics-data]
enabled = true
verify_jwt = true
import_map = "./functions/get-analytics-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-analytics-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-analytics-data/*.html" ]

[functions.registrar-visita]
enabled = true
verify_jwt = true
import_map = "./functions/registrar-visita/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/registrar-visita/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/registrar-visita/*.html" ]

[functions.mark-notifications-seen]
enabled = true
verify_jwt = true
import_map = "./functions/mark-notifications-seen/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mark-notifications-seen/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mark-notifications-seen/*.html" ]

[functions.mark-notification-read]
enabled = true
verify_jwt = true
import_map = "./functions/mark-notification-read/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mark-notification-read/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mark-notification-read/*.html" ]

[functions.post-reply-and-notify]
enabled = true
verify_jwt = true
import_map = "./functions/post-reply-and-notify/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/post-reply-and-notify/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/post-reply-and-notify/*.html" ]

[functions.handle-like-and-notify]
enabled = true
verify_jwt = true
import_map = "./functions/handle-like-and-notify/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/handle-like-and-notify/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/handle-like-and-notify/*.html" ]

[functions.validate-turnstile]
enabled = true
verify_jwt = true
import_map = "./functions/validate-turnstile/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-turnstile/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-turnstile/*.html" ]
